version: "3.7"
services:

  surveyeditor:
    image: 'surveyeditordev'
    container_name: surveyeditor-integrated
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - PROTOCOL=http://
      - SERVER_NAME=${DOMAIN?Variable not set}
      - PORT
      - BASE_PATH=/surveyeditor
      - MONGODB_URL=mongodb://user:userpass@mongodb:27017/data?retryWrites=true&w=majority
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.${STACK_NAME?Variable not set}-surveyeditor-http.rule=PathPrefix(`/surveyeditor`)
      - traefik.http.services.${STACK_NAME?Variable not set}-surveyeditor.loadbalancer.server.port=${PORT}
      - traefik.http.routers.${STACK_NAME?Variable not set}-surveyeditor-http.middlewares=surveyeditor-stripprefix
      - traefik.http.middlewares.surveyeditor-stripprefix.stripprefix.prefixes=/surveyeditor
    networks:
      - traefik-public
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

networks:
  traefik-public:
    external: true
